### PR TITLE
webdev shenanigans

### PR DESCRIPTION
**Pull request by ArjixWasTaken**
Made typescript output any artifacts inside a `dist` directory, which is ignored by git.
Moved all the source code (except serve.js) in the `src` directory.

Deleted all existing artifacts (`.mjs`).
Added a github workflow for publishing the artifacts to a `dist` branch (for github pages).

You can see the deployment [here](https://arjixwastaken.github.io/koil/).

Before merging, you will need to make a `dist` branch, you don't have to do anything special to it, it just has to exist.

### CODE REVIEW

**Comment by ArjixWasTaken** [comment]
I managed to resist the urge of including vite as well.

**Comment by rexim** [comment]
No. We didn't need a custom GitHub Action Deployment step before. You just added the need for it for no reason and increased the complexity of the deployment.

**Comment by rexim** [comment]
Also, refactoring: https://github.com/tsoding/koil/blob/b89feda19aa5dd8ced5e249febbb6ece27cf9b1e/CONTRIBUTING.md

**Comment by ArjixWasTaken** [comment]
> No. We didn't need a custom GitHub Action Deployment step before. You just added the need for it for no reason and increased the complexity of the deployment.

That is the spirit of web dev, I stayed true to the PR's title.

**Pull request closed without merging**
