### PR TITLE
New buffer structure to store display data with size

### PR DESCRIPTION
**Pull request by AdamStrojek**
I noticed that during stream you were passing around screen width and height over and over again. This information are already available for WASM module, but are never stored. This patch is to address this. Later you can use this approach to migrate sprites and walls textures.

Important note: I put array with data as first element in structure to avoid pointer manipulation to access underneath buffer. Purpose was to limit pointer manipulation in TypeScript, unfortunately C3 is doing some shenanigans with structures and prepends some 24 byte long header. 

Because pointers are passed as integers you can avoid a lot of verification and type checking when using this approach. C3 is just "restoring" proper structure from its memory, what will eliminate a lot of castings.

### CODE REVIEW

**Comment by rexim** [comment]
All of this does not matter, because it's an intermediate code as we are translating TS to C3. All of that will go away and get tucked under a wasm module where we can just use proper convenient structures and types. No need to fuzz about the code that is bound to get removed anyway.

**Comment by AdamStrojek** [comment]
I also remember this explanation during stream and this is reason why I finally just put +24 instead of trying to decompile C3 to find reason. I made this patch for fun to check one concept how to cooperate between wasm and js

**Comment by rexim** [comment]
Plus this is just a refactoring. As [CONTRIBUTING.md](https://github.com/tsoding/koil/blob/89d18ff54a01c3a11d29d61288fb3608f606b949/CONTRIBUTING.md) I do not consider it because I have limited resources to maintain my projects, sorry

**Comment by AdamStrojek** [comment]
Not a problem, have fun in next streams!

**Pull request closed without merging**
