### PR TITLE
experimental transform types

### PR DESCRIPTION
**Pull request by sakgoyal**
* added `--experimental-strip-types` support in required `22.6.0` node version
* client cannot use ts files so js files kept there
* server files moved to only use ts
  * diabled js emit for serve and build
* use ESM syntax for built and serve file by adding `"type": "module"` in `package.json`
* use built in `Record` Type
* update TS to 5.5 which was a big update to improve inference

### CODE REVIEW

**Comment by rexim** [comment]
I personally don't really understand what exact specific problem this is solving except "let's just using this shiny new thing"

**Comment by sakgoyal** [comment]
I agree. it does feel nice to use the "shiny new thing". but my reasoning is that I think it makes more sense to avoid the build step and have less files needed to run this. 

it can also avoid having the issue of accidentally forgetting the build step since you are running the actual ts file directly.

**Comment by sakgoyal** [comment]
updated to support a newer flag that has less limitations

**Comment by sakgoyal** [comment]
yes. this is only a node feature. so browsers (the client) cannot use ts files yet. but the server can do it. 

so yes. we aren't completely avoiding the build step. it just makes it a shorter step and results in fewer files

**Comment by rexim** [comment]
So I don't see any point in introducing this then. Especially since once everything is rewritten in C3 we gonna completely remove TypeScript and just be left with a small amoutn of JavaScript.

**Pull request closed without merging**
